import type { ComponentType } from "react";

/**
 * One demo per component. Each is loaded only on its own page.
 * The file contents are also shown in the Code tab, so keep them copy-paste friendly.
 */
export const demos: Record<string, () => Promise<{ default: ComponentType }>> = {
  accordion: () => import("./accordion"),
  alert: () => import("./alert"),
  "alert-dialog": () => import("./alert-dialog"),
  "aspect-ratio": () => import("./aspect-ratio"),
  attachment: () => import("./attachment"),
  avatar: () => import("./avatar"),
  badge: () => import("./badge"),
  breadcrumb: () => import("./breadcrumb"),
  bubble: () => import("./bubble"),
  button: () => import("./button"),
  "button-group": () => import("./button-group"),
  calendar: () => import("./calendar"),
  card: () => import("./card"),
  carousel: () => import("./carousel"),
  chart: () => import("./chart"),
  checkbox: () => import("./checkbox"),
  collapsible: () => import("./collapsible"),
  combobox: () => import("./combobox"),
  command: () => import("./command"),
  "context-menu": () => import("./context-menu"),
  "data-table": () => import("./data-table"),
  "date-picker": () => import("./date-picker"),
  dialog: () => import("./dialog"),
  direction: () => import("./direction"),
  drawer: () => import("./drawer"),
  "dropdown-menu": () => import("./dropdown-menu"),
  empty: () => import("./empty"),
  field: () => import("./field"),
  "hover-card": () => import("./hover-card"),
  input: () => import("./input"),
  "input-group": () => import("./input-group"),
  "input-otp": () => import("./input-otp"),
  item: () => import("./item"),
  kbd: () => import("./kbd"),
  label: () => import("./label"),
  marker: () => import("./marker"),
  menubar: () => import("./menubar"),
  message: () => import("./message"),
  "message-scroller": () => import("./message-scroller"),
  "native-select": () => import("./native-select"),
  "navigation-menu": () => import("./navigation-menu"),
  pagination: () => import("./pagination"),
  popover: () => import("./popover"),
  progress: () => import("./progress"),
  questionnaire: () => import("./questionnaire"),
  "radio-group": () => import("./radio-group"),
  resizable: () => import("./resizable"),
  "scroll-area": () => import("./scroll-area"),
  select: () => import("./select"),
  separator: () => import("./separator"),
  sheet: () => import("./sheet"),
  sidebar: () => import("./sidebar"),
  skeleton: () => import("./skeleton"),
  slider: () => import("./slider"),
  spinner: () => import("./spinner"),
  switch: () => import("./switch"),
  table: () => import("./table"),
  tabs: () => import("./tabs"),
  textarea: () => import("./textarea"),
  toast: () => import("./toast"),
  toggle: () => import("./toggle"),
  "toggle-group": () => import("./toggle-group"),
  tooltip: () => import("./tooltip"),
  typography: () => import("./typography"),
};
